// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeLPuWLB1NbBhoQoWoGS1ZNILKdZIrXIM',
    appId: '1:532220759328:web:88a7fde1c5de8839575b45',
    messagingSenderId: '532220759328',
    projectId: 'phoneauth-f9f9f',
    authDomain: 'phoneauth-f9f9f.firebaseapp.com',
    storageBucket: 'phoneauth-f9f9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB85JK5MULsPJRXBzcpS1IJOrafKk6kFKQ',
    appId: '1:532220759328:android:6c5a4b60ea0e72cf575b45',
    messagingSenderId: '532220759328',
    projectId: 'phoneauth-f9f9f',
    storageBucket: 'phoneauth-f9f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmHbDkBinlMbYtvPDYi4VUiUvfS5T8f7I',
    appId: '1:532220759328:ios:7b85580d60b87e54575b45',
    messagingSenderId: '532220759328',
    projectId: 'phoneauth-f9f9f',
    storageBucket: 'phoneauth-f9f9f.appspot.com',
    iosClientId: '532220759328-fihvpunsisrieca0j2cc6tu54p360447.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonelogin',
  );
}
